name: Rapport de bug
description: Aidez à améliorer le programme en envoyant des rapports de bug
title: "[Bug] "
labels: [bug]
assignees:
  - amostin
body:
  - type: markdown
    attributes:
      value: |
        Merci pour le temps que vous prenez pour nous aider !
- type: textarea
  id: repro
  attributes:
    label: Comment reproduire le bug ?
    description: "Étapes pour reproduire le comportement: "
    value: |
      1.
      2.
      3.
      ...
