name: Rapport de bug
description: Aidez à améliorer le programme en envoyant des rapports de bug
title: "[Bug] "
labels: [bug, ]
assignees:
  - amostin
body:
  - type: markdown
    attributes:
      value: |
        Merci pour le temps que vous prenez pour nous aider !

